name: openvpn_dart
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/mysteriumnetwork/openvpn_dart
repository: https://github.com/mysteriumnetwork/openvpn_dart

environment:
  sdk: "^3.0.0"
  flutter: 3.35.3

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mysteriumvpn.openvpn_dart
        pluginClass: OpenvpnDartPlugin
      ios:
        pluginClass: OpenvpnDartPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: OpenvpnDartPlugin
        sharedDarwinSource: true
      windows:
        pluginClass: OpenvpnDartPluginCApi
